---
version: "3"

services:
  api:
    container_name: dm-api
    build:
      context: .
    stdin_open: true
    tty: true
    restart: unless-stopped
    volumes:
      - ./src:/var/www
    ports:
      - "5000:5000"
      - "8001:8000"
    env_file:
      - .env
    networks:
      - backend
  # db:
  #   image: mongo:latest
  #   container_name: dm-mongo
  #   restart: unless-stopped
  #   volumes:
  #     - mongodb_data:/data/db
  #   ports:
  #     - "27016:27017"
  #   env_file:
  #     - .env
  #   networks:
  #     - backend
  browserless:
    image: browserless/chrome:latest
    container_name: dm-browserless
    ports:
<<<<<<< HEAD
      - "3001:3000"
    env_file:
      - .env
    networks:
      - backend
volumes:
  mongodb_data:
=======
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    secrets:
      - source: quote_txt
        target: quote.txt
>>>>>>> b1949f9b301eef109150dfcb1febfa376e3997d8

networks:
  backend:
